### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [gtm-templates-simo-ahava/gtag-get-api#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) The documentation link [https://www.simoahava.com/custom-templates/gtag-get-api](https://www.simoahava.com/custom-templates/gtag-get-api) provided in the manifest file is not valid. Please provide valid url.
![Screenshot 2020-12-22 at 12 37 12 PM](https://user-images.githubusercontent.com/53495700/102931259-ea123180-4452-11eb-8453-6abbfb8ac2fa.png)

**Comment by sahava** [comment]
Hi @praveena-pappu - the broken link has been fixed.
